### ISSUE TITLE
How can i obtain own voculbulary?

### ISSUE THREAD

**Issue by pzy5678** [Chen-Wang-CUHK/ExHiRD-DKG#11]
I want to train a chinese model, and how can i  got a ".vocab.ot" file? 
I can't open it.
Do i need to train a OpenNMT-py model to obtain it? If so , what should i do to process the data?

**Comment by Chen-Wang-CUHK** [comment]
The "vocab.pt" is built by Opennmt preprocess code from the original data. We did the following preprocess: 
  
  1. Directly use the preprocess coder of OpenNMT-py to obtain the vocabulary file from the original data, i.e., "vocab.pt".
  2. Use the obtained vocabulary file to filter out the keyphrases whose tokens are all "UNK". If all the keyphrases of a data sample are filtered, we remove the data sample.
  3. Preprocess the filtered data using the Openomt-py preprocess code. In this step, a new vocabulary file is produced but we cannot use it since it will make some already-remained keyphrases become all "UNK" and we need to filter the data again and again. We need to use the vocabulary produced in Step 1.

You can also skip the filtering step and directly preprocess the data using Opennmt-py. Based on my observations, such a filtering process is reasonable but only slightly affects the model performance.


> I want to train a chinese model, and how can i got a ".vocab.ot" file?
> I can't open it.
> Do i need to train a OpenNMT-py model to obtain it? If so , what should i do to process the data?

**Comment by pzy5678** [comment]
Thanks。
